<a href="https://colab.research.google.com/github/thanugeorge13/BIS_LAB/blob/main/parallel_cellular.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#network routing

import numpy as np

# Grid size (3x3)
rows, cols = 3, 3

# Large number to represent infinity
INF = 9999

# Initialize cost grid
cost = np.full((rows, cols), INF)

# Random or fixed link costs (use fixed for clarity)
link_costs = np.array([
    [1, 2, 3],
    [4, 1, 2],
    [3, 2, 1]
])

# Define source and destination
source = (0, 0)
destination = (2, 2)

# Destination cost is 0 (base of propagation)
cost[destination] = 0

# Neighbor directions (up, down, left, right)
directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]

# Run parallel cellular updates
for iteration in range(6):  # a few steps are enough for 3x3
    new_cost = cost.copy()
    for i in range(rows):
        for j in range(cols):
            if (i, j) == destination:
                continue  # skip destination
            neighbor_costs = []
            for di, dj in directions:
                ni, nj = i + di, j + dj
                if 0 <= ni < rows and 0 <= nj < cols:
                    neighbor_costs.append(cost[ni, nj] + link_costs[i, j])
            if neighbor_costs:
                new_cost[i, j] = min(neighbor_costs)
    cost = new_cost
    print(f"Iteration {iteration + 1}:")
    print(cost)
    print("-" * 30)

print(f"✅ Final estimated cost from {source} → {destination}: {cost[source]}")

Iteration 1:
[[10000 10001 10002]
 [10003 10000     2]
 [10002     2     0]]
------------------------------
Iteration 2:
[[10002 10002     5]
 [10004     3     2]
 [    5     2     0]]
------------------------------
Iteration 3:
[[10003     5     5]
 [    7     3     2]
 [    5     2     0]]
------------------------------
Iteration 4:
[[6 5 5]
 [7 3 2]
 [5 2 0]]
------------------------------
Iteration 5:
[[6 5 5]
 [7 3 2]
 [5 2 0]]
------------------------------
Iteration 6:
[[6 5 5]
 [7 3 2]
 [5 2 0]]
------------------------------
✅ Final estimated cost from (0, 0) → (2, 2): 6
